### ISSUE TITLE
GTInspector integration -> show live contents preview

### ISSUE THREAD

**Issue by peteruhnak** [pharo-contributions/file-dialog#4]

**Comment by CafeKrem** [comment]
I did something like that I have an architecture of previewer and I define a previewer when the selected index change it's opens the StInspector (Spec inspector)  into the notePresenter
![inspectorFileDialog](https://user-images.githubusercontent.com/36420329/62706609-31c82280-b9f0-11e9-90eb-27a7a4483d6e.png)
