### ISSUE TITLE
cull:cull: missing on ByteSymbol

### ISSUE THREAD

**Issue by bergel** [pharo-contributions/file-dialog#5]
Hi!

In a Pharo 60408, I have loaded FileDialog, using
```
Metacello new
		    baseline: 'FileDialog';
		    repository: 'github://peteruhnak/file-dialog/repository';
		    load
```

The following example
```
(FDOpenDirectoryDialog new
		defaultFolder: FileLocator imageDirectory asFileReference;
		openModal) inspect
```
raises an error: 
![screen shot 2017-02-27 at 4 55 27 pm](https://cloud.githubusercontent.com/assets/393742/23377149/957db256-fd0d-11e6-86dd-495c711b0f42.png)

**Comment by peteruhnak** [comment]
Seems to be broken only in Pharo 6, but should be fixed now. Thanks!

**Comment by bergel** [comment]
Excellent! Works perfectly!
