### ISSUE TITLE
Access the directory where the user cancel the file dialog

### ISSUE THREAD

**Issue by juliendelplanque** [pharo-contributions/file-dialog#9]
Sometimes, it may be needed to know where the user stopped to browse the file system before the file dialog was cancelled. For example to reopen the file dialog at this place. Thus, it would be cool to have this information remembered in some place (an instance variable?).

**Comment by peteruhnak** [comment]
I'm not aware of any browser in any system that would remember the location if the dialog was _canceled_.
Normally the location is preserved when the dialog was confirmed, and that can be also dependent on some context, I think based on the file extension?

So I guess the later option could be added? I think there is a problem that normally the default location is _explicitly defined_ (somewhere in the depths of UIManager), in which case it should imho be honored.
